[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://cheramandalam-finance.onrender.com/api"
  VITE_FIREBASE_AUTH_ENABLED = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
